# Generated by Django 6.0.7 on 2026-10-08 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(db_index=True, help_text='Unique customer application tracking reference (e.g. FCA-482910)', max_length=64, unique=True)),
                ('service', models.CharField(db_index=True, help_text='Service identifier e.g. bank-fca, ins-motor, prop-stand', max_length=64)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('national_id', models.CharField(db_index=True, help_text='Zimbabwe National ID or Passport Number', max_length=64)),
                ('date_of_birth', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=40)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('address', models.TextField()),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Structured multi-step form answers submitted by user.')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Application',
                'verbose_name_plural': 'Onboarding Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service', 'status'], name='accounts_on_service_81f173_idx'), models.Index(fields=['national_id', 'email'], name='accounts_on_nationa_3a7ea4_idx')],
            },
        ),
    ]
