# Generated by Django 6.0.7 on 2026-10-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=120)),
                ('action_text', models.CharField(max_length=80)),
                ('action_href', models.CharField(max_length=255)),
                ('badge', models.CharField(blank=True, max_length=80, null=True)),
                ('icon_name', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CorporateFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('confirmed', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique slug identifier (e.g. fy2025-results)', max_length=120, unique=True)),
                ('category', models.CharField(choices=[('shareholder', 'Shareholder Notice'), ('customer', 'Customer Notice'), ('regulatory', 'Regulatory Circular'), ('operational', 'Operational Notice')], default='customer', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('date_display', models.CharField(help_text='e.g. 28 March 2026', max_length=60)),
                ('summary', models.TextField()),
                ('circular_ref', models.CharField(blank=True, help_text='e.g. ZSE: CBZ / CIR-03-2026', max_length=100, null=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('file_size', models.CharField(blank=True, help_text='e.g. PDF · 3.4 MB', max_length=50, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(help_text='e.g. Dividend & Results', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='communicati_categor_9fa5ea_idx'), models.Index(fields=['is_urgent', 'is_active'], name='communicati_is_urge_591878_idx')],
            },
        ),
    ]
