# Generated by Django 6.0.7 on 2026-10-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Product category within subsidiary, e.g. accounts, loans, cards, personal, business, residential', max_length=50)),
                ('item_id', models.CharField(blank=True, help_text='Unique product identifier slug, e.g. platinum_card', max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pricing', models.CharField(default='Contact us for rates', max_length=100)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='subsidiaries.subsidiary')),
            ],
            options={
                'ordering': ['subsidiary', 'category', 'order', 'name'],
                'indexes': [models.Index(fields=['subsidiary', 'category'], name='products_pr_subsidi_aceac3_idx')],
            },
        ),
    ]
