# Generated by Django 6.0.7 on 2026-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('iso', models.CharField(max_length=4)),
                ('cur', models.CharField(max_length=50)),
                ('dial', models.CharField(max_length=10)),
                ('illustrative', models.BooleanField(default=False)),
                ('regulator', models.CharField(blank=True, max_length=200, null=True)),
                ('pcur', models.CharField(max_length=10)),
                ('rate', models.FloatField(default=1.0)),
                ('rates', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
    ]
