# Generated by Django 6.0.7 on 2026-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('branch_type', models.CharField(choices=[('branch', 'Full Branch'), ('agency', 'Agency / Express'), ('atm', '24/7 ATM')], default='branch', max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, default='+263 8677004050', max_length=50)),
                ('hours', models.CharField(default='Mon - Fri: 08:00 - 15:00 | Sat: 08:00 - 11:30', max_length=100)),
                ('services', models.JSONField(blank=True, default=list, help_text='List of available services e.g. Forex, Cash, Mortgages, ATMs')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['city', 'name'],
            },
        ),
    ]
