# Generated by Django 6.0.7 on 2026-10-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonOption',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('entity', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AssetOption',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('entity', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoverOption',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('tier', models.CharField(max_length=50)),
                ('base_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_percentage', models.FloatField(default=0.0, help_text='Annual rate percentage applied to vehicle value (e.g. 0.045 for 4.5% comprehensive)')),
                ('features', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_addons', models.JSONField(blank=True, default=list)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_value_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reg_number', models.CharField(blank=True, max_length=50)),
                ('overnight_location', models.CharField(blank=True, max_length=100)),
                ('monthly_premium_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_premium_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.assetoption')),
                ('cover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.coveroption')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
